services:

  sae-nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
      - "8090:8090"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/app/backend
      - ./frontend:/app/frontend

  sae-frontend:
    build: 
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true

  sae-backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/app/backend

  sae-mysql:
    image: mysql:8
    volumes:
      - database:/var/lib/mysql
      - ./docker/mysql/sql_import_scripts/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "sae401"
  
  sae-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: sae-mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8070:80"
    depends_on:
      - sae-mysql

  sae-mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8060:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
      MP_DATABASE: /data/mailpit.db
    volumes:
      - mailer-database:/data

volumes:
  database:
  mailer-database:
