nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:8090'] # Change this to match your frontend URL
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        max_age: 3600
    paths:
        '^/posts': # Applies to /posts API
            allow_origin: ['http://localhost:8090']
            allow_methods: ['GET', 'POST', 'OPTIONS', 'PUT', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization']
        '^/update':  # Only applies to the /update route
            allow_origin: ['http://localhost:8090']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PATCH', 'PUT', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization']
             